# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}
- {name: 'Sponsors', folder: 'pages', file: 'sponsors.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://github.com/uproot-robotics'}

# Customize site text
pagination:
  next_page: 'Older'
  previous_page: 'Newer'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Similar Posts:'

post_date_prefix: 'Written on'
